services:
  - type: web
    name: chatbot-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker --timeout 90 --bind 0.0.0.0:$PORT
